### ISSUE TITLE
Make it work with more wallets than nami

### ISSUE THREAD

**Issue by GGAlanSmithee** [GGAlanSmithee/cardano-lucid-blockfrost-proxy-example#2]
The example relies on `window.cardano[walletName].experimental.on("networkChange", cb)`, so any other wallet needs to support this API as well. Let's find out which does.

**Comment by GGAlanSmithee** [comment]
Would probably be OK to work around the above with hard refreshes as fallback. Will try with eternl.

**Comment by jinglescode** [comment]
Just thought of sharing that this project would have way lesser boilerplate codes and be more responsive if you use [Mesh](https://mesh.martify.io/). Great work for making this work nevertheless. Wonderful and keep building on Cardano.

**Comment by GGAlanSmithee** [comment]
Hi @jinglescode

Thanks for showing interest in the project. This specific github repository exists as a response to [this github issue](https://github.com/spacebudz/lucid/issues/25) (which is mentioned in the README), so it doesn't really makes sense to use another library in place of cardano-lucid. Having said that, thanks for linking Mesh, I will check it out!

In regards to this repo having a lot of boilerplate code, I am in the process of creating a react hook version of cardano-lucid in a separate npm package, which will make the code contained in this project only pertain to the examples themselves.

**Comment by GGAlanSmithee** [comment]
I will close this issue, since I will keep this repository as a minimum example, but I've added a link to [use-cardano](https://www.github.com/use-cardano/use-cardano) for anyone who is looking for a more complete package.

BTW @jinglescode you guys are doing a really good job with Mesh, been following your progress on Github and watched recent interviews! :100:
